### ISSUE TITLE
Harvest Integration

### ISSUE THREAD

**Issue by curiouscrusher** [nguyenhuy/github_dashboard#1]
First off – this is a great dashboard you set up! 
I started working on creating a dashboard for office use just the other day, and I was looking for a way to integrate Harvest hours, and found this setup you have. 

I went through configuring the harvest widgets with my info and everything, but when I deployed to Heroku nothing shows up in the hour count. No "0" or any other value. Any chance you could provide some insight on something I missed or overlooked. 

Thanks!

**Comment by nguyenhuy** [comment]
I'm happy to help you :) I guess an error log or some code would be useful for debugging. 
Also it's been a long time since I worked on this project and Harvest API may have been changed since then, so we need to check it as well.

**Comment by curiouscrusher** [comment]
Thanks so much! 
I guess a quick easy test would be for you to plug in your Harvest credentials on your end, and see if they work. And if they do that just means I’ve messed something up. If they don’t that means Harvest may have changed the API and broke it. 
Sound good?

-- 
Nate Holland

On July 24, 2014 at 11:33:23 AM, nguyenhuy (notifications@github.com) wrote:

I'm happy to help you :) I guess an error log or some code would be useful for debugging.
Also it's been a long time since I worked on this project and Harvest API may have been changed since then, so we need to check it as well.

**Comment by nguyenhuy** [comment]
Sounds right. I will find time for this within this week. I hope it is ok for you.

**Comment by curiouscrusher** [comment]
That’s great! 
Thanks so much for your help, I really appreciate it! :)
-- 
Nate Holland

On July 24, 2014 at 1:22:41 PM, nguyenhuy (notifications@github.com) wrote:

Sounds right. I will find time for this within this week. I hope it is ok for you.

**Comment by nguyenhuy** [comment]
First of all, I'm sorry for this late response.

I've managed to get Harvest integration up and running on Heroku (again). I think it stopped working because Harvest API was changed. I ran `bundle update` to update gems, including `harvested` to v2.0.0.
A working snapshot of the project can be found on `master` branch.

Cheers :)
